# Numpy Array Tutorials

## 1: arrays 1D 2D 3D
## 2: array zeros , ones , identity(), arrange() , empty, lines space,using copy ,random, 
## 5: using copy

## ......................finish


# create numpy N_D array(1D, 2D,3D)
### create 1 D array

In [3]:
import numpy as np

In [11]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [15]:
# print its dimention
arr1.ndim

1

In [16]:
#print its shape  (in one dimention it just give the values)
arr1.shape

(5,)

In [25]:
len(arr1)  # len function basically give the number of dimentions (khu dalta chunky one dimention d nu srip values rkai)

5

### create 2D array

In [10]:

arr2=np.array([[1,2,3,4],[3,4,5,6]])
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [20]:
arr2.ndim

2

In [22]:
arr2.shape

(2, 4)

In [23]:
len(arr2)

2

### Create 3D Dimentional array

In [27]:
arr3=np.array([[[1,2],[5,6]],[[6,7],[10,2]]]) # list within a list within a list ( draw in copy the 3 d array)
arr3

array([[[ 1,  2],
        [ 5,  6]],

       [[ 6,  7],
        [10,  2]]])

In [30]:
arr3.ndim  # print 3 dimention array

3

In [29]:
arr3.shape

(2, 2, 2)


# 2: array zeros , ones , identity(), arrange() , empty, lines space, random, 

In [37]:
arr4=np.zeros((3,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr5=np.ones((3,3),dtype=int)   # in the above by default the array give float but it we want to integer then we mention to it
arr5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
arr6=np.identity(3)   # or arr6 =np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
arr7=np.arange(10) # np.arange function in NumPy is used to create an array containing a sequence of numbers
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# create an array start from 5 , stop 50, and stepping by 5
#Function Definition: np.arange(start, stop, step, dtype=None)  genral formula
arr8=np.arange(5,50,5)
arr8

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [58]:
arr9=np.linspace(2,3,10)  #When you use np.linspace(2, 3, 10), it generates 10 evenly spaced values between 2 and 3,
arr9

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [60]:
arr10=arr9.copy()
arr10

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [65]:
arr11=np.random.rand(1,10,1)  '''  Using np.random.rand(1, 10, 1)
The function np.random.rand(1, 10, 1) creates an array of random numbers between 0 and 1 with the specified shape. Let’s break down the shape (1, 10, 1):

1: The first dimension has 1 element.
10: The second dimension has 10 elements.
1: The third dimension has 1 element.
The output will be a 3D array (with dimensions 1x10x1) filled with random numbers between 0 and 1. '''

arr11  

#This means you're creating an array with 1 group, each containing 10 rows, and each row containing 1 number


array([[[0.33221243],
        [0.99084001],
        [0.19551994],
        [0.8967585 ],
        [0.55493201],
        [0.27540267],
        [0.53524253],
        [0.88173081],
        [0.29323285],
        [0.89270011]]])

# Properties And Attribute

### 1:shape
### 2:Ndin
### 3:size
### 4:itemsize
### 5:dtype
### 6:astype()
### and some more operation line min, max, mean, median, and so on


In [3]:

arr2=np.array([[1,2,3,4],[3,4,5,6]])
arr2

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [4]:
# the above two already complete
arr2.size

8

In [5]:
arr2.itemsize    # it the repesent the like this data is inter then it show 4

4

In [6]:
arr2.dtype    # show the type

dtype('int32')

In [7]:
arr2.astype("float")   # astype function convet one types data to another type

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.]])

# indexing, slicing ,interation

## indexcing and silicing

In [45]:
ar1=np.arange(24)
ar1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [10]:
ar2=ar1.reshape(6,4)
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
ar11=ar1[ar1>=3]=10   # condition 
ar11

10

In [62]:
even=ar1[ar1%2==0] # for even number 
even

array([ 0,  2, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10])

In [14]:
ar1[:,2]   # specific 3rd columns

array([ 2,  6, 10, 14, 18, 22])

In [15]:
ar1[:,2:]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [24]:
ar2[4:,2:]

array([[18, 19],
       [22, 23]])

In [26]:
ar2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [113]:
w1=np.arange(24).reshape(6,4)
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [114]:
w1[[0,2,4]]  # find the row 1, row 2, row 3

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [116]:
w1[[0,2,4],1:3]

array([[ 1,  2],
       [ 9, 10],
       [17, 18]])

## iteration

In [28]:
ar2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [29]:
for i in ar2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [32]:
for i in np.nditer(ar2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# numpy operations
### 1: A+B
### 2: A-B
### 3: A*B
### 4: A*4
### 5: A+5
### 6: A*B(element wise null)
### 7: ADOT(B)
### 8: A*=b


In [34]:
ar3=np.array([1,2,3,4])  # for addition
ar4=np.array([5,6,7,8])
sum_a=ar3+ar4
sum_a


array([ 6,  8, 10, 12])

In [35]:
ar3=np.array([1,2,3,4])# multiplication
ar4=np.array([5,6,7,8])
sum_a=ar3*ar4
sum_a

array([ 5, 12, 21, 32])

In [36]:
ar3=np.array([1,2,3,4])  # for subtraction
ar4=np.array([5,6,7,8])
sum_a=ar3-ar4
sum_a

array([-4, -4, -4, -4])

In [37]:
ar5=ar3*4
ar5

array([ 4,  8, 12, 16])

In [47]:
aa1=np.arange(6).reshape(2,3)    # because order ba ye hm bara bara
aa2=np.arange(6,12).reshape(3,2)
aaa4=aa1.dot(aa2)
aaa4

array([[ 28,  31],
       [100, 112]])

In [48]:
aaa4.max()

112

In [49]:
aaa4.min()


28

In [51]:
aaa4.mean()
aaa4.std()

38.499188303131795

In [53]:
np.median(aaa4)     '''aaa4.mean()  
                    np.median(aaa4) when i am accessing the mean() then direct function used
                    but if i access median  then used np.medain why short and used very simple ord'''

65.5

In [59]:
arrray=np.array([1.3,2.3,3.3,5.7,4.8],dtype=int)
arrray


array([1, 2, 3, 5, 4])

# Reshaping numpy array
## 1: Reshape
## 1: ravel
## 1: transpose
## 1: stacking
## 1: spliting



In [71]:
a1=np.arange(20)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
a2=a1.reshape(5,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
a3=a2.ravel()  # wapse da 5 by 4  matrix na 1D array julay
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
a4=a2.transpose()  # trpose of a matrix or only write T
a4

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [83]:
f=np.arange(6).reshape(2,3)
f

array([[0, 1, 2],
       [3, 4, 5]])

In [84]:
f1=np.arange(6,12).reshape(2,3)
f1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [92]:
f2=np.hstack((f,f1))  #  horizental arrays ku add karty hai
f2

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [93]:
f2=np.vstack((f,f1))  #  varticaly arrays ku add karty hai
f2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [100]:
np.vsplit(f2,2)      # splitw function used to split the array in equal part
                    # same vartical spliting

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]])]

# Part 10 - Indexing with Boolean Arrays

In [122]:
ar8=np.random.randint(low=10,high=100,size=24).reshape(6,4)
ar8

array([[62, 52, 31, 97],
       [17, 61, 78, 93],
       [61, 39, 15, 48],
       [69, 28, 18, 18],
       [29, 45, 29, 73],
       [58, 90, 30, 57]])

In [140]:
ar8=np.random.randint(10,100,24).reshape(6,4) # same the by default it get first low then high then size
ar8

array([[17, 81, 65, 67],
       [61, 32, 61, 29],
       [74, 20, 15, 78],
       [51, 42, 20, 36],
       [44, 21, 73, 46],
       [79, 32, 32, 83]])

In [123]:
ar8[ar8>50 ]

array([62, 52, 97, 61, 78, 93, 61, 69, 73, 58, 90, 57])

In [124]:
ar8[(ar8>50)&(ar8%2==0)]  # greater to 50 values then only even number

array([62, 52, 78, 58, 90])

In [127]:
ar8[(ar8>50)&(ar8%2==0)]=1 # che 50 seva ye aw bya pa ke even ye nu hge za bandy 1 walagawa
ar8

array([[ 1,  1, 31, 97],
       [17, 61,  1, 93],
       [61, 39, 15, 48],
       [69, 28, 18, 18],
       [29, 45, 29, 73],
       [ 1,  1, 30, 57]])

In [132]:
x=np.array([1,2,3,4])
y=np.array([12,34,56,8])
x,y

(array([1, 2, 3, 4]), array([12, 34, 56,  8]))